import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header style={{ padding: "1rem", backgroundColor: "#262020", color: "#fff" }}>
          <nav>
            <Link href="/" style={{ marginRight: "1rem", color: "#9c3737", textDecoration: "none" }}>
              Home
            </Link>
            <Link href="/about" style={{ color: "#9c3737", textDecoration: "none" }}>
              About
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
